services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./services/api-gateway/.env
    depends_on:
      - rabbitmq
      - postgres
      - redis
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=notification_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - dns_net

  # user-service:
  #   build: ./services/user-service
  #   networks:
  #     - dns_net

  # email-service:
  #   build: ./services/email-service
  #   networks:
  #     - dns_net

  # push-service:
  #   build: ./services/push-service
  #   networks:
  #     - dns_net

  # template-service:
  #   build: ./services/template-service
  #   networks:
  #     - dns_net

  # infra
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dns_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dns_net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dns_net

networks:
  dns_net:
    driver: bridge

volumes:
  pgdata:
