services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./services/api-gateway/.env.docker
    depends_on:
      - rabbitmq
      - postgres
      - redis
      - user-service
      - email-service
      - push-service
      - template-service
    networks:
      - dns_net

  user-service:
    build: ./services/user-service
    ports:
      - "8001:8000"
    env_file:
      - ./services/user-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - dns_net

  email-service:
    build: ./services/email-service
    ports:
      - "8003:8003"
    env_file:
      - ./services/email-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - template-service
    networks:
      - dns_net

  push-service:
    build: ./services/push-service
    ports:
      - "8005:8005"
    env_file:
      - ./services/push-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - template-service
      - user-service
    networks:
      - dns_net

  template-service:
    build: ./services/template-service
    ports:
      - "8002:8002"
    env_file:
      - ./services/template-service/.env
    depends_on:
      - postgres
      - redis
    networks:
      - dns_net

  # infra
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dns_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dns_net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dns_net

networks:
  dns_net:
    driver: bridge

volumes:
  pgdata:
